FROM node:22-alpine
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

ENV NEXT_TELEMETRY_DISABLED=1
# Polling required for file-watch inside Docker on macOS/Windows
ENV WATCHPACK_POLLING=true

CMD ["yarn", "dev"]
