#!/usr/bin/env node
/**
 * Reads brand.config.json → writes app/generated-tokens.css
 * Run: node scripts/generate-tokens.mjs  (or: yarn tokens)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const brand = JSON.parse(readFileSync(join(root, "brand.config.json"), "utf8"));

const { colors: c, darkColors: d, radius: r } = brand;

const css = `/* Auto-generated by \`yarn tokens\` — edit brand.config.json, then re-run */

@theme {
  /* Primary */
  --color-forest:        ${c.primary};
  --color-forest-light:  ${c.primaryLight};

  /* Accent */
  --color-sage:          ${c.accent};
  --color-sage-light:    ${c.accentLight};
  --color-sage-dark:     ${c.accentAccessible};

  /* Surfaces */
  --color-surface:       ${c.surface};
  --color-surface-muted: ${c.surfaceMuted};
  --color-auren-border:  ${c.border};

  /* Text */
  --color-text-primary:  ${c.textPrimary};
  --color-text-secondary:${c.textSecondary};
  --color-text-muted:    ${c.textMuted};

  /* Semantic */
  --color-auren-success: ${c.success};
  --color-auren-warning: ${c.warning};
  --color-auren-error:   ${c.error};
  --color-auren-info:    ${c.info};

  /* Radius */
  --radius-card:  ${r.card};
  --radius-pill:  ${r.pill};
  --radius-input: ${r.input};

  /* Shadows */
  --shadow-subtle:   0 1px 3px rgba(23, 37, 34, 0.06);
  --shadow-card:     0 4px 20px rgba(23, 37, 34, 0.06);
  --shadow-elevated: 0 12px 40px rgba(23, 37, 34, 0.10);

  /* Motion */
  --ease-auren:      cubic-bezier(0.22, 1, 0.36, 1);
  --duration-fast:   120ms;
  --duration-normal: 200ms;
  --duration-slow:   350ms;

  /* Typography */
  --font-sans: "Inter", ui-sans-serif, system-ui, sans-serif;

  /* Spacing */
  --spacing-page-mobile:  20px;
  --spacing-page-tablet:  32px;
  --spacing-page-desktop: 48px;
}

:root {
  --auren-bg:         ${c.bg};
  --auren-primary-fg: ${c.primaryFg};
  --auren-secondary:  ${c.secondary};
  --auren-input:      ${c.input};
}

.dark {
  color-scheme: dark;

  --auren-bg:         ${d.bg};
  --auren-primary-fg: ${d.primaryFg};
  --auren-secondary:  ${d.secondary};
  --auren-input:      ${d.input};

  --color-surface:        ${d.surface};
  --color-surface-muted:  ${d.surfaceMuted};
  --color-text-primary:   ${d.textPrimary};
  --color-text-secondary: ${d.textSecondary};
  --color-text-muted:     ${d.textMuted};
  --color-sage-dark:      ${d.accentAccessible};
  --color-auren-border:   ${d.border};
  --color-forest:         ${d.primary};
  --color-forest-light:   ${d.primaryLight};
  --color-auren-error:    ${d.error};
  --color-auren-success:  ${d.success};
}
`;

writeFileSync(join(root, "app/generated-tokens.css"), css);
console.log("✓ app/generated-tokens.css written");
