services:
  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../.env.dev
    environment:
      NODE_ENV: development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
